jdbc:
  driverClassName: "com.p6spy.engine.spy.P6SpyDriver"
  url: "jdbc:p6spy:mariadb://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8"
  username: ""
  password: ""

jwt:
  secret: "seppiko-wagashi"
  issuer: "Wagashi"
